#### 1. 배열 생성, indexing, slicing, Assigning values, reshape, resize 연습

##### (1)1~25 사이의 2의 배수 12개로 1차원 배열(a) 생성, 출력
#####  (2)a 의 인덱스 2~5의 요소값을 -20으로 수정, 출력
#####  (3)a를 이용하여 3X4 배열(b)로 변경, 출력
#####  (4)a를 2X6 배열로 변경, 출력
#####  (5)a를 1행의 모든 값을 추출하여 a1을 만들고, a1의 모든 값을 0으로 변경, 출력


In [1]:
import numpy as np


In [2]:
a = np.arange(2,25,2)
print(a)


[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [3]:
a[2:6] = -20
print(a)


[  2   4 -20 -20 -20 -20  14  16  18  20  22  24]


In [4]:
b = a.reshape(3,4)
print(b)

[[  2   4 -20 -20]
 [-20 -20  14  16]
 [ 18  20  22  24]]


In [5]:
a = a.reshape(2,6)
print(a)

[[  2   4 -20 -20 -20 -20]
 [ 14  16  18  20  22  24]]


In [6]:
a1 = a[0:1]
a1 = np.zeros((1,6))
print(a1)

[[0. 0. 0. 0. 0. 0.]]


### 2. 배열 연산, 함수 연습
#### (1)1~10 사이의 임의의 값으로 3X3 배열 x, y생성, 출력



In [7]:
x = np.round(np.random.random((3,3))*9+1)
y = np.round(np.random.random((3,3))*9+1)

print("X = " ,x)
print("Y = ", y)


X =  [[ 9.  2.  3.]
 [ 1. 10.  8.]
 [ 3.  9.  9.]]
Y =  [[ 5. 10.  9.]
 [ 5.  7.  5.]
 [ 2.  3.  9.]]


#### 2)x의 1, 2 행의 모든 열추출, 출력


In [8]:
print(x[1:3, :])

[[ 1. 10.  8.]
 [ 3.  9.  9.]]


#### 3)x의 2열의 모든 행 추출, 출력


In [32]:
print(x[0::,2:3:2])

[[3.]
 [8.]
 [9.]]


#### 4)x의 0,2열의 1,2 행 추출, 출력


In [22]:

print(x[1:3:,0:3:2])

[[1. 8.]
 [3. 9.]]


#### 5)x의 각행의 합, 각 열의 합, 출력


In [11]:
print("X의 각 열의 합 = ",x.sum(axis=0))
print("X의 각 행의 합 = ",x.sum(axis=1))



X의 각 열의 합 =  [13. 21. 20.]
X의 각 행의 합 =  [14. 19. 21.]


#### 6)x의 각행의 최대값, 각 열의 최대값, 출력


In [12]:
print("X의 각 열의 최대값 =",x.max(axis=0))
print("X의 각 행의 최대값 = ",x.max(axis=1))

X의 각 열의 최대값 = [ 9. 10.  9.]
X의 각 행의 최대값 =  [ 9. 10.  9.]


#### (7)x, y 배열의 합, 곱, 내적을 구하여 출력


In [13]:
print("x = ",x)
print("y = ",y)
print("x, y 배열의 합 = ", x + y)
print("x, y 배열의 곱 = ",x @ y)
print("x, y 배열의 내적 = ",x.dot(y))


x =  [[ 9.  2.  3.]
 [ 1. 10.  8.]
 [ 3.  9.  9.]]
y =  [[ 5. 10.  9.]
 [ 5.  7.  5.]
 [ 2.  3.  9.]]
x, y 배열의 합 =  [[14. 12. 12.]
 [ 6. 17. 13.]
 [ 5. 12. 18.]]
x, y 배열의 곱 =  [[ 61. 113. 118.]
 [ 71. 104. 131.]
 [ 78. 120. 153.]]
x, y 배열의 내적 =  [[ 61. 113. 118.]
 [ 71. 104. 131.]
 [ 78. 120. 153.]]


### 3. 배열복사, 결합 연습
#### (1) 1~3, 10~30, 100~300 3개의 1차원 배열(a1,a2,a3)을 생성하여 행으로 결합하여 y배열 생성
#### (2) y배열의 0,2 열을 복사하여 y1, 1열을 복사하여 y2 생성
#### (3) y1, y2를 결합하여 yy배열 생성
#### (4)yy 배열에서  20~200 범위의 값만을  추출하여  합, 평균 출력

배열 복사
1. 1 ㅅ씩 10씩 100씩 증가
3.  문제 마스크로 만들어서 뽑아 내고 결합
비연속 적인 배열을 만들어서 추출
2,3 문제 reshape 를 하여 열단위 결합


In [14]:
a1 = np.arange(1,4,1)
a2 = np.arange(10,40,10)
a3 = np.arange(100,400,100)


#print(a2)
#print(a3)

In [15]:
y = np.vstack([a1,a2,a3])

print("y = ",y)

y =  [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [16]:
y1 = y[::1,::2].copy()

print("y1 = ",y1)

y1 =  [[  1   3]
 [ 10  30]
 [100 300]]


In [17]:
y2 = y[::,1:2].copy()
print("y2 = ",y2)

y2 =  [[  2]
 [ 20]
 [200]]


In [18]:

#y1.reshape(1,6)
#y2.reshape(1,-1)

yy = np.hstack([y1.reshape(1,6),y2.reshape(1,-1)])


print("yy(열로 합침)= ", yy)





yy(열로 합침)=  [[  1   3  10  30 100 300   2  20 200]]


In [19]:
mask = (yy >= 20) & (yy <=200)

print("mask = ",mask)
print("yy[mask] = ",yy[mask])
print("yy 배열의 20~200 사이의 합 = ",yy[mask].sum())
print("yy 배열의 20~200 사이의 평균 = ",yy[mask].sum()/yy[mask].size)



mask =  [[False False False  True  True False False  True  True]]
yy[mask] =  [ 30 100  20 200]
yy 배열의 20~200 사이의 합 =  350
yy 배열의 20~200 사이의 평균 =  87.5
